version: '3.9'

networks:
  wazuh-net:
    driver: bridge

volumes:
  yara-rules: {}
  sigma-rules: {}

services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.4.0
    container_name: wazuh-manager
    networks:
      - wazuh-net
    ports:
      - "1514:1514/udp"
      - "1515:1515"
    volumes:
      - yara-rules:/var/ossec/ruleset/yara-rules
      - sigma-rules:/var/ossec/ruleset/sigma-rules
    environment:
      - WAZUH_PASSWORD=Secret123
  
  wazuh-agent:
    image: wazuh/wazuh-agent:4.4.0
    container_name: wazuh-agent
    depends_on:
      - wazuh-manager
    networks:
      - wazuh-net
    environment:
      - MANAGER_IP=wazuh-manager
    volumes:
    - ./atomic-red-team:/atomic
  
  yara-dev:
    image: yara-dev-env
    container_name: yara-dev
    networks:
      - wazuh-net
    volumes:
      - ./rules/yara:/rules
      - ./yara-dev/scan.sh:/yara/scan.sh
    command: 
      - /bin/bash
      - -c
      - |
        while true; do
          sleep 3600
        done
  
  sigma-dev:
    image: sigma-converter
    container_name: sigma-dev
    networks:
      - wazuh-net
    volumes:
      - ./rules/sigma:/sigma-src
      - ./converted-rules:/converted
      - ./sigma-dev/convert.sh:/opt/sigma/convert.sh
    command: 
      - /bin/bash
      - -c
      - |
        while true; do
          sleep 3600
        done
