version: '3.9'

networks:
  wazuh-net:
    driver: bridge

volumes:
  yara-rules: {}
  sigma-rules: {}

services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.4.0
    container_name: wazuh-indexer
    networks:
      - wazuh-net
    environment:
      - INDEXER_MEM=512m
      - node.name=wazuh-indexer
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
  wazuh-manager:
    image: wazuh/wazuh-manager:4.4.0
    container_name: wazuh-manager
    networks:
      - wazuh-net
    environment:
      - INDEXER_URL=https://wazuh-indexer:9200
      - WAZUH_PASSWORD=Secret123
    ports:
      - "1514:1514/udp"
      - "1515:1515"
    depends_on:
      - wazuh-indexer
  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.4.0
    container_name: wazuh-dashboard
    networks:
      - wazuh-net
    environment:
      - INDEXER_URL=https://wazuh-indexer:9200
      - DASHBOARD_PASSWORD=Secret123
    ports:
      - "5601:5601"
    depends_on:
      - wazuh-indexer
  
  yara-dev:
    build: ./yara-dev
    container_name: yara-dev
    networks:
      - wazuh-net
    volumes:
      - ./rules/yara:/rules
      - ./yara-dev/scan.sh:/yara/scan.sh
    command: 
      - /bin/bash
      - -c
      - |
        while true; do
          sleep 3600
        done
  
  sigma-dev:
    image: sigma-converter
    container_name: sigma-dev
    networks:
      - wazuh-net
    volumes:
      - ./rules/sigma:/sigma-src
      - ./converted-rules:/converted
      - ./sigma-dev/convert.sh:/opt/sigma/convert.sh
    command: bash -c "while true; do sleep 3600; done"
